defaultEntryPoints = ["http"]
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.auth.forward]
    address = "http://sso/auth"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain  = "guard.local"
watch   = true